MVC-Application/MVCLoginApplication/Models/pcExamCenterListModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCLoginApplication.Models
{
    public class pcExamCenterListModel
    {
        public string txtExamFilter { get; set; }

        public string txtFilterNm { get; set; }

        public List<SelectListItem> ddlEditDistrict { get; set; }

        public string txtSelectedDistrictValue { get; set; }
        public IEnumerable<pcExamCenterList> gvpcExamCenterList { get; set; }

    }
        public class pcExamCenterList
        {
            public string txtCenterCode { get; set; }

            public string txtCenterName { get; set; }
            public string txtCenterAddress {  get; set; }
            public string txtTelephoneNo { get; set; }
    }
}

MVC-Application/MVCLoginApplication/Models/pcLoginModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MVCLoginApplication.Models
{
    public class pcLoginModel
    {
        public string txtusername { get; set; }

        public string txtemailid { get; set; }
        public string txtpassword { get; set; }
    }
}

MVC-Application/MVCLoginApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCLoginApplication.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVC-Application/MVCLoginApplication/Controllers/pcExamCenterListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Web;
using System.Web.Mvc;
using MVCLoginApplication.Models;
using MVCLoginApplication.pcClass;

namespace MVCLoginApplication.Controllers
{
    public class pcExamCenterListController : Controller
    {
        // GET: pcExamCenterList

        pcExamCenterListModel opcExamCenterListModel=new pcExamCenterListModel();

        public ActionResult Index()
        {
            int intRecFound = 0;
            List<SelectListItem> ddlDistrictList = new List<SelectListItem>();
            intRecFound = pcClsExamCenter.pcFillddlDistrict(ref ddlDistrictList);

            opcExamCenterListModel.ddlEditDistrict = ddlDistrictList;
            
            return View("pcExamCenterListView",opcExamCenterListModel);
        }
    }
}

MVC-Application/MVCLoginApplication/Controllers/pcExamCenterListCopyController.cs
using MVCLoginApplication.Models;
using MVCLoginApplication.pcClass;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCLoginApplication.pcClassCopy;

namespace MVCLoginApplication.Controllers
{
    public class pcExamCenterListCopyController : Controller
    {
        // GET: pcExamCenterListCopy

        pcExamCenterListModel opcExamCenterListModel = new pcExamCenterListModel();

        public ActionResult Index()
        {
            int intRecFound = 0;
            List<SelectListItem> ddlDistrictList = new List<SelectListItem>();
            intRecFound=pcExamCenterListClass.pcFillDistrictList(ref ddlDistrictList);
            opcExamCenterListModel.ddlEditDistrict=ddlDistrictList;

            return View("pcExamCenterListCopyView",opcExamCenterListModel);
        }
        [HttpPost]
        public ActionResult pcBtnShow(pcExamCenterListModel opcExamCenterListModel)
        {
            opcExamCenterListModel.gvpcExamCenterList = pcExamCenterListClass.pcExamCenterListData(opcExamCenterListModel.txtSelectedDistrictValue, opcExamCenterListModel.txtFilterNm);
            return PartialView("pcExamCenterPartialView",opcExamCenterListModel);
        }

        //public ActionResult LoadPartial(bool hideDiv = false)
        //{
        //    ViewBag.HideDiv = hideDiv;
        //    return PartialView("pcExamCenterPartialView", opcExamCenterListModel);
        //}
    }
}

MVC-Application/MVCLoginApplication/Controllers/pcLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCLoginApplication.Models;


namespace MVCLoginApplication.Controllers
{
    public class pcLoginController : Controller
    {
        // GET: pcLogin
       // pcLoginModel pcLoginModelData=new pcLoginModel();
        public ActionResult Index()
        {
            return View("pcLoginView");
        }

        [HttpPost]

        public ActionResult LoginButtonClick(string Username,string Password)
        {
            return View();  
        }

       

    }
}

MVC-Application/MVCLoginApplication/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

MVC-Application/MVCLoginApplication/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

MVC-Application/MVCLoginApplication/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

MVC-Application/MVCLoginApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <!--<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>-->
            @*<div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>*@
        <!--</div>
    </nav>-->
    @*<div class="container body-content">*@
        @RenderBody()
       
       
    @*</div>*@

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

MVC-Application/MVCLoginApplication/Views/pcExamCenterList/pcExamCenterListView.cshtml
@model MVCLoginApplication.Models.pcExamCenterListModel
@{
    ViewBag.Title = "pcExamCenterListView";
}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"></script>

    <!-- jQuery & jQuery UI -->
    <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script src="https://code.jquery.com/ui/1.14.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.14.1/themes/base/jquery-ui.css">

    <style>
        * {
            font-family: Tahoma;
        }

        .headerDiv {
            max-width: 600px; /* Limit the maximum width */
            margin: auto; /* Center the div */
        }

        .btnOrg {
            background: rgb(255, 132, 9);
            border: none;
            outline: none;
            border-radius: 4px;
            padding: 8px;
            color: #fff;
        }

        .bgGrey {
            background: #ccc;
        }
    </style>
</head>

<body>
    @using (Html.BeginForm(null, null, new { @area = "", @id = string.Empty }, FormMethod.Post, new { @id = "pcExamCenterListView", @name = "pcExamCenterListView", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="container-fluid">
            <div class="border mt-3 headerDiv">
                <label class="form-label form-label-sm w-100 p-1 bgGrey">List OF Exam Centers</label>
                <label class="form-label form-label-sm p-1">Search Exam Center</label>
                <div class="d-flex flex-column flex-sm-row gap-4 p-1">
                    <div class="d-flex flex-column flex-sm-row gap-2 col-md-6">
                        <label class="form-label form-label-sm"> Show Exam Center's that</label>
                        <select class="form-select form-select-sm">
                            <option value="">Starts with</option>
                            <option value="">Contains</option>
                            <option value="">Ends with</option>
                            <option value="">Is Exactly Like</option>
                        </select>
                    </div>
                    <input type="text" class="form-control" aria-describedby="inputGroup-sizing-sm">
                </div>
                <div class="d-flex flex-column flex-sm-row gap-2 p-2">
                    <label class="form-label form-label-sm">From the District</label>
                    <select class="form-select form-select-sm "
                            id="ddlEditDistrict"
                            name="txtSelectedDistrictValue">
                        @{
                            foreach (var item in Model.ddlEditDistrict)
                            {
                                <option value="@item.Value". @(item.Selected == true ? "selected=\"selected\"" : "")>@item.Text</option>

                                }
                            }
                    </select>
                </div>
                <div class="d-flex justify-content-end p-1 bgGrey">
                    <button class="btn btn-sm me-2 btnOrg btnShow" type="button">Show</button>
                    <button class="btn btn-sm me-2 btnOrg" type="reset">Refresh</button>
                </div>
            </div>

            <div class="hiddenDiv" style="display:none; padding: 0px 20px;">
                <label class="form-label form-label-sm mt-2">
                    <b> List of Exam Centers</b>
                </label>

                <div class="table-responsive">
                    <table class="table table-bordered" style="font-size: 13px; border: 1px solid #ccc;">
                        <thead style="font-size: 14px;">
                            <tr class="text-center">
                                <th style="width:8%;">Sr. No.</th>
                                <th>Center Code</th>
                                <th style="width: 70%;">Center Name and Address</th>
                                <th>Tel. No.</th>
                            </tr>
                            <tr>
                                <th colspan="4">District: AHILYANAGAR</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>1.</td>
                                <td>17210092</td>
                                <td>
                                    <b>ABASAHEB KAKADE JR. COLLEGE, SHEVGAON</b>
                                    <p>ABASAHEB KAKADE JR.COLLEGE,SHEVGAON, SHEVGAON, SHEVGAON, AHILYANAGAR</p>
                                </td>
                                <td>0-8805982127</td>
                            </tr>
                            <tr>
                                <td>2.</td>
                                <td>17210178</td>
                                <td>
                                    <b>ABHINAV COMPUTER TECHNICAL INSTITUTE</b>
                                    <p>TRIMURTI CHAWK, NEAR BHARAT GAS GODOWN, PIPELINE ROAD , AHILYANAGAR, AHILYANAGAR, Nagar, AHILYANAGAR</p>
                                </td>
                                <td>0-9921384896</td>
                            </tr>
                            <tr>
                                <td>3.</td>
                                <td>17210178</td>
                                <td>
                                    <b>ANUKUL COMPUTERS</b>
                                    <p>7285, CENTRAL BANK ROAD, OPP. DASI PAN, AHILYANAGAR, AHILYANAGAR, Nagar, AHILYANAGAR</p>
                                </td>
                                <td>0-9970415929</td>
                            </tr>
                            <tr>
                                <td>4.</td>
                                <td>17210520</td>
                                <td>
                                    <b>ANVI COMPUTER INSTITUTE</b>
                                    <p>kolgaon village, SHRIGONDA, Shrigonda, AHILYANAGAR</p>
                                </td>
                                <td>0-7385585656</td>
                            </tr>
                            <tr>
                                <td>5.</td>
                                <td>17210219</td>
                                <td>
                                    <b>BITS COMPUTERS</b>
                                    <p>SHOP NO 1,KALE COMPLEX,IN FRONT OF SHRIKRISHNA COLLECTION,NEAR KAKASAHEB MHASKE VIDYALAYA,ADRSHNAGAR NAGAPUR.AHILYANAGAR., AHILYANAGAR, Nagar, AHILYANAGAR</p>
                                </td>
                                <td>0-8888875883</td>
                            </tr>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    }

</body>


<script>
    $(document).ready(function(){
        $('.btnShow').click(function(){
            $('.hiddenDiv').css('display','');
        })
    })
</script>

MVC-Application/MVCLoginApplication/Views/pcExamCenterListCopy/pcExamCenterListCopyView.cshtml
@model MVCLoginApplication.Models.pcExamCenterListModel
@{
    ViewBag.Title = "pcExamCenterListView";
}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"></script>

    <!-- jQuery & jQuery UI -->
    <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script src="https://code.jquery.com/ui/1.14.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.14.1/themes/base/jquery-ui.css">

    <style>
        * {
            font-family: Tahoma;
        }

        .headerDiv {
            max-width: 600px; /* Limit the maximum width */
            margin: auto; /* Center the div */
        }

        .btnOrg {
            background: rgb(255, 132, 9);
            border: none;
            outline: none;
            border-radius: 4px;
            padding: 8px;
            color: #fff;
        }

        .bgGrey {
            background: #ccc;
        }

       /* .mainDiv{
            position:sticky;
            top:0%;
            z-index:1;
            overflow:auto;
        }*/
    </style>
</head>

<body>
    @using (Html.BeginForm(null, null, new { @area = "", @id = string.Empty }, FormMethod.Post, new { @id = "pcExamCenterListCopyView", @name = "pcExamCenterListCopyView", enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        <div class="container-fluid mainDiv">
            <div class="border mt-3 headerDiv">
                <label class="form-label form-label-sm w-100 p-1 bgGrey">List OF Exam Centers</label>
                <label class="form-label form-label-sm p-1">Search Exam Center</label>
                <div class="d-flex flex-column flex-sm-row gap-4 p-1">
                    <div class="d-flex flex-column flex-sm-row gap-2 col-md-6">
                        <label class="form-label form-label-sm"> Show Exam Center's that</label>
                        <select class="form-select form-select-sm" id="txtExamFilter" name="txtExamFilter">
                            <option value="1">Starts with</option>
                            <option value="2">Contains</option>
                            <option value="3">Ends with</option>
                            <option value="4">Is Exactly Like</option>
                        </select>
                    </div>
                    <input type="text" id="txtFilterNm" name="txtFilterNm" class="form-control" aria-describedby="inputGroup-sizing-sm">
                </div>
                <div class="d-flex flex-column flex-sm-row gap-2 p-2">
                    <label class="form-label form-label-sm">From the District</label>
                    <select class="form-select form-select-sm "
                            id="ddlEditDistrict"
                            name="txtSelectedDistrictValue">
                        @{
                            foreach (var item in Model.ddlEditDistrict)
                            {
                                <option value="@item.Value". @(item.Selected == true ? "selected=\"selected\"" : "")>@item.Text</option>

                            }
                         }       

                    </select>
                </div>
                <div class="d-flex justify-content-end p-1 bgGrey">
                    <button class="btn btn-sm me-2 btnOrg btnShow" type="button">Show</button>
                    <button class="btn btn-sm me-2 btnOrg btnRefresh" type="reset">Refresh</button>
                </div>
            </div>

            <div id="gvPartialView">

            </div>
        </div>
    }

</body>


<script>
    $(document).ready(function(){
        $('.btnShow').click(function(){
            /*$('.hiddenDiv').css('display', '');*/
            debugger;
            var formControlValues = $('#pcExamCenterListCopyView').serialize();

            $.ajax({
                url: '@Url.Action("pcBtnShow", "pcExamCenterListCopy")',
                type: "POST",
                async: true,
                cache: false,
                contentType: "application/x-www-form-urlencoded",
                data: formControlValues,
                dataType: "html",
                success: function (result, status, xhr)
                {
                    $('#gvPartialView').html('');
                    $('#gvPartialView').html(result);

                }
            })
        })

        //$('.btnRefresh').click(function () {
        //    $('#hiddenDiv').hide(); // Hides the div in the partial view
        //});

        $('.btnRefresh').click(function () {
            $('#gvPartialView').html('');
        });

    })

    
</script>

MVC-Application/MVCLoginApplication/Views/pcExamCenterListCopy/pcExamCenterPartialView.cshtml
@model MVCLoginApplication.Models.pcExamCenterListModel
@{
    ViewBag.Title = "pcExamCenterPartialView";
}
@if (Model.gvpcExamCenterList != null)
{
    if (Model.gvpcExamCenterList.Count() != 0)
    {
        string strTable_DataNm = "gvpcExamCenterList";
        string strTmpData = "";
        string strNumber = "";
        <div id="gvPartialView" class="hiddenDiv" style="padding: 0px 80px; ">
            <label class="form-label form-label-sm mt-2">
                <b> List of Exam Centers</b>
            </label>

            <div class="table-responsive" style="max-height:400px;">
                <table class="table table-bordered" style="font-size: 13px; border: 1px solid #ccc;" >
                    <thead style="font-size: 14px; overflow: auto; position:sticky; top:0%; z-index:1; background:#fff ">
                        <tr class="text-center">
                            <th>Sr.No</th>
                            <th style="width:12%;">Center Code</th>
                            <th style="width:70%;">Center Name and Address </th>
                            <th style="width:12%;">Telephone No.</th>
                        </tr>
                        <tr>
                            <th colspan="4">District: @Model.txtSelectedDistrictValue</th>
                        </tr>
                    </thead>
                    @{ 
                        int FirstNM = 1;
                    }
                   
                    @for (int i = 0; i < Model.gvpcExamCenterList.Count() - 1; i++)
                            {
                        <tr>
                            <td>
                               
                                <input value="@FirstNM" style="border:none; outline:none;" readonly/>
                            </td>
                            <td>
                                <input value="@Model.gvpcExamCenterList.ElementAt(i).txtCenterCode" style="border:none; outline:none" readonly/>
                            </td>
                            <td>
                                <div class="w-100">
                                    <input value="@Model.gvpcExamCenterList.ElementAt(i).txtCenterName" class="fw-bold w-100" style="border:none;outline:none;" readonly/>
                                   <br />
                                   <textarea class="w-100 auto-resize" style="border: none; outline: none; overflow: hidden; resize: none;" readonly>@Model.gvpcExamCenterList.ElementAt(i).txtCenterAddress</textarea>
                                </div>
                                
                            </td>
                            <td>
                                <input  value="@Model.gvpcExamCenterList.ElementAt(i).txtTelephoneNo" style="border:none; outline:none;" readonly/>
                            </td>
                        </tr>
                                        FirstNM++;
                                    }



                </table>
            </div>
        </div>

    }

}

MVC-Application/MVCLoginApplication/Views/pcLogin/pcLoginView.cshtml
@*@{
        ViewBag.Title = "pcLoginView";
    }*@

<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap 5 CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"></script>

    <!-- jQuery & jQuery UI -->
    <script src="https://code.jquery.com/jquery-3.7.1.js"></script>
    <script src="https://code.jquery.com/ui/1.14.1/jquery-ui.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.14.1/themes/base/jquery-ui.css">

    <style>

        #form-struct {
            top: 50%;
            left: 50%;
            position: absolute;
            transform: translate(-50%,-50%);
        }
    </style>
</head>

    <body class="bg-light">

        <div class="container-fluid">
            <div class="p-5">
                <form id="form-struct" class="bg-white p-4 bg-body rounded shadow">
                    <div class="row mb-3 mt-3">
                        <div class="col-md-4">
                            <label for="inptusrname" id="lblusername">UserName</label>
                        </div>

                        <div class="col-md-8">
                            <input type="text" class="form-control" id="txtusername" name="txtusername"  />
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-md-4">
                            <label for="inptemail" id="lblemail">Email</label>
                        </div>

                        <div class="col-md-8">
                            <input type="text" class="form-control" id="txtemailid" />
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-md-4">
                            <label for="inptpwd" id="lblpwd" class="col-md-2 col-form-label">Password</label>
                        </div>

                        <div class="col-md-8">
                            <input type="password" class="form-control" id="txtpassword" name="txtpassword" />
                        </div>
                    </div>

                    <div class="d-flex gap-2">
                        <input type="button" id="btnlogin" class="btn btn-primary w-100" value="Login"  />

                        <input type="button" id="btnexit" class="btn btn-primary w-100" value="Exit" />
                    </div>

                </form>

            </div>
        </div>

    </body>

</html>

<script>
    $('#btnlogin').click(function () {
        debugger;
        var usrname = document.getElementById("txtusername").value.trim();
        if (usrname == "") {
            alert("Please Enter UserName");
            return false;
        }
        if (usrname.length< 2) {
            alert("Username must be atleast 2 characters..");
            return false;
        }
        var email = document.getElementById("txtemailid").value.trim();
        var emailregx= /^[a-zA-Z0-9._%+-]+@@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
        if (email == "") {
            alert("Please Enter your Email address");
            return false;
        }
        if (!emailregx.test(email)) {
            alert("Please Enter a valid Email address");
            return false;
        }

        var pwd = document.getElementById("txtpassword").value.trim();

        if (pwd === "") {
          alert("Please enter password!");
         return false;
        }

        if (pwd.length < 8) {
           alert("Password must be at least 8 characters long.");
           return false;
        }

        if (!/[A-Z]/.test(pwd)) {
         alert("Password must contain at least one uppercase letter.");
         return false;
        }

        if (!/[a-z]/.test(pwd)) {
          alert("Password must contain at least one lowercase letter.");
          return false;
        }

        if (!/[0-9]/.test(pwd)) {
          alert("Password must contain at least one digit.");
          return false;
        }

        if (!/[@@$!%*?&]/.test(pwd)) {
          alert("Password must contain at least one special character (@@ $ ! % * ? &).");
           return false;
        }

    });
</script>